### ISSUE TITLE
Deprecated selector in `northem-dark-atom-syntax/index.less`

### ISSUE THREAD

**Issue by ucyo** [arcticicestudio/northem-dark-atom-syntax#12]
In `northem-dark-atom-syntax/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor,
atom-text-editor::shadow,
:host` => `atom-text-editor,
atom-text-editor.editor,atom-text-editor`

* `atom-text-editor .bracket-matcher .region,
atom-text-editor::shadow .bracket-matcher .region,
:host .bracket-matcher .region` => `atom-text-editor .bracket-matcher .region,
atom-text-editor.editor .bracket-matcher .region,atom-text-editor .bracket-matcher .region`

* `atom-text-editor .cursor,
atom-text-editor::shadow .cursor,
:host .cursor` => `atom-text-editor .cursor,
atom-text-editor.editor .cursor,atom-text-editor .cursor`

* `atom-text-editor .indent-guide,
atom-text-editor::shadow .indent-guide,
:host .indent-guide` => `atom-text-editor .indent-guide,
atom-text-editor.editor .indent-guide,atom-text-editor .indent-guide`

* `atom-text-editor .invisible,
atom-text-editor::shadow .invisible,
:host .invisible` => `atom-text-editor .invisible,
atom-text-editor.editor .invisible,atom-text-editor .invisible`

* `atom-text-editor .invisible-character,
atom-text-editor::shadow .invisible-character,
:host .invisible-character` => `atom-text-editor .invisible-character,
atom-text-editor.editor .invisible-character,atom-text-editor .invisible-character`

* `atom-text-editor .line.cursor-line,
atom-text-editor::shadow .line.cursor-line,
:host .line.cursor-line` => `atom-text-editor .line.cursor-line,
atom-text-editor.editor .line.cursor-line,atom-text-editor .line.cursor-line`

* `atom-text-editor .selection .region,
atom-text-editor::shadow .selection .region,
:host .selection .region` => `atom-text-editor .selection .region,
atom-text-editor.editor .selection .region,atom-text-editor .selection .region`

* `atom-text-editor .wrap-guide,
atom-text-editor::shadow .wrap-guide,
:host .wrap-guide` => `atom-text-editor

[..] Error message too long

**Comment by arcticicestudio** [comment]
➡️ Resolved in #14
