### ISSUE TITLE
No support for MJML

### ISSUE THREAD

**Issue by caseymhunt** [arcticicestudio/northem-dark-atom-syntax#2]
[MJML](https://github.com/mjmlio/mjml) files, which are, for the sake of argument, an extension of HTML syntax, are _not_ supported by this theme.

**Comment by arcticicestudio** [comment]
Syntax Highlighting language is detected by the file extension, will add it as subtype to the HTML file.
Is MJML 100% compatible to HTML or are there any differences or maybe additions I've to add?
Nevertheless, I will bump the version so you can easly update the package and would appreciate feedback.

**Comment by arcticicestudio** [comment]
Released version [`0.15.0`](https://github.com/arcticicestudio/northem-dark-atom-syntax/releases/tag/v0.15.0) including [MJML](https://atom.io/packages/language-mjml) support.

**Comment by caseymhunt** [comment]
Excellent! I do not know of any specific support necessary for `MJML` but I will keep an eye out as I use the theme.

**Comment by caseymhunt** [comment]
<img width="1178" alt="screenshot 2016-02-15 16 53 01" src="https://cloud.githubusercontent.com/assets/2065615/13062503/c883986a-d404-11e5-9511-26f79a00d0af.png">

Just some quick feedback- I really like this theme but I do suggest colorizing content between tags and attribute values differently. Being that they are both white, it is difficult to differentiate between tag content between <tag> and </tag> and element attributes. (Seen above)

This is particularly a problem with HTML (and subsequently, MJML).

**Comment by arcticicestudio** [comment]
This is one of the items on my backlog, but I am not conclusive about the color to use for the attribute values due to the limited colors of my [Northem](https://github.com/arcticicestudio/northem) color palette. I don't want to change the color of text elements, but if I use the `light-blue` color for attributes it is difficult to see the difference between the attribute name and the value.

**Comment by arcticicestudio** [comment]
I've created a new issue [[#3](https://github.com/arcticicestudio/northem-dark-atom-syntax/issues/3)] to discuss about a improvement.
