### ISSUE TITLE
Improve colour differences for HTML/MJML

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/northem-dark-atom-syntax#3]
Related to the comment of @caseymhunt in issue [#2](https://github.com/arcticicestudio/northem-dark-atom-syntax/issues/2#issuecomment-184431350).
The HTML/MJML color for attribute names and the associated value is hard to distinguish from the normal text content.
![github-atom-package-northem-dark-atom-syntax-issue-3-current](https://cloud.githubusercontent.com/assets/7836623/13091167/29cee4c6-d4fa-11e5-8315-046bb754c64c.png)
### Possible solutions:

**1)** Attribute names are colored `lime` and the associated values are colored `aqua`, quoted string begin- and end symbols are `blue`
- :+1: Better element differentiation
- :-1: Conflicts with JavaScript function color
- :fist: Can disrupt the overall theme color logic/appearance

You can check out the [`improvement/ghi-3-testbranch-solution-1`](https://github.com/arcticicestudio/northem-dark-atom-syntax/tree/improvement/ghi-3-testbranch-solution-1) test branch.

![github-atom-package-northem-dark-atom-syntax-issue-3](https://cloud.githubusercontent.com/assets/7836623/13091082/b1b98f18-d4f9-11e5-83a3-8f3229d66e78.png)

**2)** Only change the quoted string begin- and end symbols to `blue` to mark better visualize the start and end of a attribute value. Normal text is not effected by this.
- :+1: Better delimitation differentiation between normal text and attribute elements
- :-1: Attribute and text colors are still the same

You can check out the [`improvement/ghi-3-testbranch-solution-2`](https://github.com/arcticicestudio/northem-dark-atom-syntax/tree/improvement/ghi-3-testbranch-solution-2) test branch.

![github-atom-package-northem-dark-atom-syntax-issue-3-solution-2](https://cloud.githubusercontent.com/assets/7836623/13091980/eceecff4-d4fd-11e5-90df-c3f4c8ef739a.png)

**3)** Only change the color of the attribute values to `light-blue` to differ from normal text.
- :+1: Better color differentiation between normal text and attribute values
- :-1: The tag, attribute name and attribute value colors are very similar and difficult to distinguish

You can check out the [`improvement/ghi-3-testbranch-solution-3`](https://github.com/arcticicestudio/northem-dark-atom-syntax/tree/improvement/ghi-3-testbranch-solution-3) test branch.

![github-atom-package-northem-dark-atom-syntax-issue-3-solution-3](https://cloud.githubusercontent.com/assets/7836623/13092210/08bfd0ba-d4ff-11e5-8f41-c41ea80ad67d.png)

**3.1)** In addition to solution **3**, use bold font style for attribute names for better differentiation
- :+1: Better color differentiation between attribute name and value
- :-1: It might seem "overloaded"/"chuncky" and may disturb/distact the coding flow

You can check out the [`improvement/ghi-3-testbranch-solution-3.1`](https://github.com/arcticicestudio/northem-dark-atom-syntax/tree/improvement/ghi-3-testbranch-solution-3.1) test branch.

![github-atom-package-northem-dark-atom-syntax-issue-3-solution-3 1](https://cloud.githubusercontent.com/assets/7836623/13092390/f4f2a20a-d4ff-11e5-910f-4f969f13a4c1.png)

**3.2)** This solution is a possible workaround to find a unified way for the PR [[#4](https://github.com/arcticicestudio/northem-dark-atom-syntax/pull/4)], please read the PR conversation for more information.  
In addition to solution **3**, use bold font style for tag names and underline attribute names for better differentiation
- :+1: Better differentiation between attribute name and value
- :+1: Better emphasis for tag names
- :-1: It might seem "overloaded"/"chuncky" and may disturb/distact the coding flow
- :fist: Maybe the tag, attribute name and attribute value colors are similar and difficult to distinguish

You can check out the [`improvement/ghi-3-testbranch-solution-3.2`](https://github.com/arcticicestudio/northem-dark-atom-syntax/tree/improvement/ghi-3-testbranch-solution-3.2) test branch.

![github-atom-package-northem-dark-atom-syntax-issue-3-solution-3 2](https://cloud.githubusercontent.com/assets/7836623/13172892/d36557ca-d6fa-11e5-8e0b-caffdde8a7c1.png)

**Comment by caseymhunt** [comment]
I like this quite a bit- do you have a branch I can pull down and test this?

**Comment by arcticicestudio** [comment]
Updated the initial post, may add some more solutions.
I will push some test branches tomorrow, it's late here, I have to get up early tomorrow for work ;)

**Comment by arcticicestudio** [comment]
Pushed test branches for all possible solutions, please read the updated the initial post for branch names.

**Comment by arcticicestudio** [comment]
I will stay with the solution **3.2** ([`improvement/ghi-3-testbranch-solution-3.2`](https://github.com/arcticicestudio/northem-dark-atom-syntax/tree/improvement/ghi-3-testbranch-solution-3.2)).

**Comment by arcticicestudio** [comment]
I've released version [`0.16.0`](https://github.com/arcticicestudio/northem-dark-atom-syntax/releases/tag/v0.16.0) which includes the merged solution.
